# Generated by Django 5.2.12 on 2026-03-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
