# Generated by Django 5.2.11 on 2026-03-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ('Books'), ('Electronics'), ('Clothing');
            """
        )
    ]
